# Generated by Django 5.0.7 on 2024-07-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stu_contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stu_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stu_name',
            new_name='Name',
        ),
    ]
