# Generated by Django 5.0.7 on 2024-07-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_stu_city_student_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
